### ISSUE TITLE
spaces in schema definition

### ISSUE THREAD

**Issue by maureeungaro** [gavalian/hipo#10]
Currently the schema parse command should not include spaces after the commas, like this:

    schemaPart.parse("pid/S,px/F,py/F,pz/F");

With spaces introduced the behavior is erratic. This should be either allowed or a proper warning / error / throw should be done if a space is present.

**Comment by gavalian** [comment]
This is not an issue anymore. Change have been made to schema parser to trim the entry names and types strings. Now spaces can be used in parse method. Everything comes out good.
