### ISSUE TITLE
python API not retrieving some bank columns

### ISSUE THREAD

**Issue by maskass** [gavalian/hipo#24]
I'm using the pyhton API you presented at the last software tutorial to read hipo files (super useful!!) but some bank columns are not retrieved correctly.
After a bit of investigation, I think that the issue is due to a column "type" missing definition.

Specifically, the missing definition is in the getType method in hipolib.py which establishes whether you want to get an int or a float. For type greater than 4 it does not enter any if case and an empty list is returned
https://github.com/gavalian/hipo/blob/master/extensions/python/hipolib.py#L97

Snippet code to be run in the hipo/extensions/python dir (I provide the path to the file I used)

```python
# to be run in hipo/extensions/python dir
from hipolib import hreader
reader = hreader('../../slib/')
f = reader.open('/work/clas12/vmascagn/ltcc_run006380.hipo')

# define the 2 banks I'm interested in for this example
reader.define('LTCC::adc')
reader.define('RUN::config')

# loop on the first 3 events, print some values just to check, and use the show method to check the column type 
counter = 0
while reader.next():
    # 2 random baks of LTCC
    print('LTCC sector',reader.getEntry('LTCC::adc', 'sector'))
    print('LTCC sector',reader.getEntry('LTCC::adc', 'ADC'))
    # 2 from RUN::config
    print('Number of run',reader.getEntry('RUN::config',"run"))
    print('RUN event',reader.getEntry('RUN::config',"event"))
    print('RUN trigger',reader.getEntry('RUN::config',"trigger"))
    reader.show('RUN::config',"trigger")
    print("-"*30)
    counter += 1
    if counter > 3:
        break
```

The output I get is this one, where I can see the "trigger" value from "RUN::config" bank is not retrieved (an empty list is always returned). I also noticed that the type is "8" which has no defined behavior as explained above.
The same is valid for "timestamp" (even if not printed here)

```
file open handle =  3
LTCC sector [3, 5]
LTCC sector [0, 186]
Number of run [6380]
RUN event [1]
RUN trigger []
	 entry =  trigger    type =  8
------------------------------
LTCC sector [5]
LTCC sector [235]
Number of run [6380]
RUN event [2]
RUN trigger []
	 entry =  trigger    type =  8
------------------------------
LTCC sector [3, 3]
LTCC sector [214, 7532]
Number of run [6380]
RUN event [5]
RUN trigger []
	 entry =  trigger    type =  8
------------------------------
LTCC sector [3]
LTCC sector [219]
Number of run [6380]
RUN event [7]
RUN trigger []
	 entry =  trigger    type =  8
```

**Comment by gavalian** [comment]
The initial implementation was for ints and floats, the doubles and longs were not yet readable.
I will add them in.

**Comment by gavalian** [comment]
The interface is added for reading LONG and DOUBLE columns from python.
A new example file is added to the directory (readclas12.py) which reads and prints 
RUN::config bank columns, and now the LONG type variables are read correctly.
@maskass, try it and let me know if it works.

**Comment by maskass** [comment]
Hi, thanks! I think there's an issue with signed/unsigned 32 bit int.
Example, using hipo-utils -dump on `/work/clas12/vmascagn/ltcc_run006380.hipo` I can see that the value for the `timestamp` in the `RUN::config` banks is (first 3 events): 3777609644, 3777624727, 3777705682

Then I run this code and from the output I can see that the unsigned 32 bit from the hipo bank ends up int a signed 32 bit int.
```python
# assuming the code runs in hipo/extensions/python dir...
from hipolib import hreader
reader = hreader('../../slib/')
f = reader.open('/work/clas12/vmascagn/ltcc_run006380.hipo')
reader.define('RUN::config')
counter = 0
while reader.next():
    print('RUN timestamp',reader.getEntry('RUN::config',"timestamp"))
    print("-"*30)
    counter += 1
    if counter > 3:
        break
```
Output
```
file open handle =  1
RUN timestamp [-517357652]
------------------------------
RUN timestamp [-517342569]
------------------------------
RUN timestamp [-517261614]
------------------------------
RUN timestamp [-517254709]
------------------------------
```

**Comment by gavalian** [comment]
the value  -517342569 is the 3777609644 in the unsigned form.
The values in the bank are signed, that's why I wrote the interface 
to return signed variable. I can of course change it to always return 
unsigned long. 
Another option is to convert the values you get into unsigned variable, isn't that possible in python?

**Comment by maskass** [comment]
Python (version 3 and later) has one int version only which is 64 bit (or arbitrary longer if necessary). I think there is no way from the number itself of knowing whether that -517342569 comes from a  3777609644 cast into a signed 32 bit int or from a -517342569. Neither from it's datatype (which will always result as `int`). It means that a proper "conversion" unaware of the data source is not possible. Of course I know it comes from a timestamp in a CLAS hipo file, so I could simply add 2**32 if negative. But I would suggest to do this in the interface.

**Comment by gavalian** [comment]
I had a feature that was not properly assigning the return types from c library. 
It's all fixed now. and I made it to convert to unsigned integer of 64 bits. 
Here is the printout of first two events from hilo-utils:

* NODE * group =  10000, item =  11, type = 11, size =       38
           run :       5988
         event :     964560
      unixtime : 1545211321
       trigger :         33
     timestamp : 114834421448
          type :          0
          mode :          0
         torus :     1.0000
      solenoid :    -1.0000
* NODE * group =  10000, item =  11, type = 11, size =       38
           run :       5988
         event :     964561
      unixtime : 1545211321
       trigger :          5
     timestamp : 114834607940
          type :          0
          mode :          0
         torus :     1.0000
      solenoid :    -1.0000

And printout from python:

event #  0  bank size =  1
event      =  [964560]
trigger    =  [33]
unixtime   =  [1545211321]
timestamp  =  [114834421448]
event #  1  bank size =  1
event      =  [964561]
trigger    =  [5]
unixtime   =  [1545211321]
timestamp  =  [114834607940]

The values for unixtime and timestamp match. Let me know if this works @maskass.

**Comment by maskass** [comment]
Perfectly fine now! Thank you.

Valerio
