### ISSUE TITLE
Streamline event-level `bank` access

### ISSUE THREAD

**Issue by c-dilks** [gavalian/hipo#30]
In the Java API, it is possible to call
```java
var particleBank = event.getBank("REC::Particle");
```
This feature does not appear to be in this C++ API.

I would like to simplify the following example as much as possible; it is an event loop which prints out the contents of `REC::Particle` for each event.

The current version of this repository requires the user to get the schema, leading to the following verbose implementation:
```cpp
int main() {
  // read input file
  hipo::reader reader;
  reader.open("data.hipo");

  // get bank schema
  hipo::dictionary factory;
  reader.readDictionary(factory);
  hipo::bank particleBank(factory.getSchema("REC::Particle"));

  // event loop
  hipo::event event;
  while(reader.next(event)) {
    event.getStructure(particleBank);
    particleBank.show();
  }
  return 0;
}
```

This is the desired implementation (or something similar):
```cpp
int main() {
  // read input file
  hipo::reader reader;
  reader.open("data.hipo");

  // event loop
  hipo::event event;
  while(reader.next(event)) {
    event.getBank("REC::Particle").show();
  }
  return 0;
}
```

**Comment by gavalian** [comment]
Funny that you mentioned it, I was just working on exactly that. And I wanted to also make the API exactly the same for C++ as it is for Java.

**Comment by gavalian** [comment]
This is an example I have for the Java library:
```
HipoReader r = new HipoReader("infile.h5");
Bank[] b = r.getBanks("REC::Particle","REC::Event");

TGCanvas c = new TGCanvas();
H1F h = new H1F("h",120,0.0,10.0);
c.draw(h);

while(r.nextEvent(b)==true){
    for(int i = 0; i < b[0].getRows(); i++) h.fill(b[0].getFloat("pz",i));
}
```
Is this along the lines you wanted?

**Comment by gavalian** [comment]
A new API is added to make reading files and getting banks more clean and short.
