### ISSUE TITLE
RHipoDS (RDataFrame reader for Hipo data) issue promoting char to short.

### ISSUE THREAD

**Issue by mholtrop** [gavalian/hipo#67]
The implementation for promoting char (type=1) to short (type=2) vectors or scalers was implemented incorrectly, causing the data to double (each data item was followed by a zero). 
This issue was observed by Whit, and reported here: https://code.jlab.org/hallb/alert/coatjava/-/merge_requests/1#note_2551

**Comment by gavalian** [comment]
I've seen several references to Whit in the e-mails and issues. What is "Whit"?

**Comment by gavalian** [comment]
Is this an issue in the HIPO library implementation of bytes and short vectors? The problem is not clearly stated.

**Comment by mholtrop** [comment]
I think that Whit is Whitney Armstrong. All references and username at JLab are “Whit”, and so I assume that is their preferred name.
Cheers,
Maurik

**Comment by mholtrop** [comment]
The “issue” that probably isn’t an issue for HIPO is that the getInt, getShort, getByte methods all return an int type variable by copy. When one uses RDataFrames, the reader puts the data for the RDataFrame in a (void *) memory block, which is then interpreted appropriately by the RDataFrame. This is much faster and more flexible than most other (i.e. typed) implementations, but it has the risk of an implementation error. The error was mine, I upcast all the types to Int, but RDataFrame was correctly reading them as short, with the result that it read 2x the numbers that were stored.

The pull request I just made should fix this issue.

Best,
Maurik

**Comment by mholtrop** [comment]
Merged
